# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecuroapp', '0004_auto_20171003_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sub_total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecuroapp.Doctor'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecuroapp.Doctor'),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_details', to='tecuroapp.Appointment'),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecuroapp.Procedure'),
        ),
    ]
