# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecuroapp', '0005_auto_20171003_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecuroapp.Doctor'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecuroapp.Doctor'),
        ),
    ]
