# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-08 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecuroapp', '0006_auto_20171008_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecuroapp.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tecuroapp.Driver'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecuroapp.Doctor'),
        ),
    ]
